FROM python:3.9-slim
COPY . /app/requirements.txt/app/requirements.txt
WORKDIR /app/

RUN pip install  --upgrade pip  \
    && pip install  -r requirements.txt\
    && rm -rf /var/cache/apk/*
    
COPY ./app/app
EXPOSE 8081

CMD ["python", "app.py"]
