version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/mydatabase
    depends_on:
      - postgres
    networks:
      - backend

  image-service:
    build:
      context: ./image-service
    container_name: image-service
    restart: always
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - image-service
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  postgres_data:

