version: "3.8"

services:
  user_service:
    build: ./UserService
    image: phrnb/user-service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - postgres-net
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgresql:5432/userdb
      - SECRET_KEY=MY_SECRET_KEY
    depends_on:
      - postgresql
    volumes:
      - ./UserService:/app

  image_processor_service:
    build: ./ImageProcessorService
    image: phrnb/image-processor-service
    restart: always
    ports:
      - "8081:8081"
    networks:
      - postgres-net
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgresql:5432/eyehealth?currentSchema=img_schema
    depends_on:
      - postgresql
    volumes:
      - ./ImageProcessorService:/app

  frontend:
    build: ./Frontend
    image: phrnb/frontend
    restart: always
    depends_on:
      - user_service
      - image_processor_service
    networks:
      - frontend-net
    ports:
      - "3000:3000"

  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - frontend-net
    environment:
      POSTGRES_DB: eyehealth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

networks:
  postgres-net:


