version: "3.8"

services:
  user_service:
    build: ./UserService
    image: phrnb/user-service
    restart: always
    ports:
      - "8000:8000"
    networks:
      - backend-net
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgresql:5432/userdb
      - SECRET_KEY=MY_SECRET_KEY
    depends_on:
      - postgresql
    volumes:
      - ./UserService:/app

  image_processor_service:
    build: ./ImageProcessorService
    image: phrnb/image-processor-service
    restart: always
    ports:
      - "8001:8001"
    networks:
      - backend-net
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgresql:5432/eyehealth?currentSchema=img_schema
    depends_on:
      - postgresql
    volumes:
      - ./ImageProcessorService:/app

  backend:
    build: ./Backend
    image: phrnb/backend
    restart: always
    depends_on:
      - user_service
      - image_processor_service
    networks:
      - backend-net

  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - backend-net
    environment:
      POSTGRES_DB: eyehealth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

networks:
  backend-net:


