FROM python:3.9-slim
COPY ./image-processor-service/requirements.txt /app/requirements.txt
WORKDIR /app
RUN
  && pip install --upgrade pip \
  && pip install -r requirements.txt \
  && rm -rf /var/cache/apk/*
COPY ./image-processor-service /app
EXPOSE 8081
CMD ["python", "app.py"]
